[package]
name = "web-app"
version = "0.1.0"
authors = ["alexandre <alexandre@senges.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
actix-files = "0.5.0"